### ISSUE TITLE
Full code release

### ISSUE THREAD

**Issue by jwang44** [SonyCSLParis/pesto#16]
Thanks for the great work! It's such a cool paper. Can't wait to train it on my own data. 
Is there an expected date for full code release? Been looking forward to it since before the conference.

**Comment by aRI0U** [comment]
Hi!
Thanks a lot for your interest in our work! I'm working on another stuff at the same time so I wouldn't be able to tell you precisely when the full code will be released, but I'll hopefully finish this before end of 2023. I keep this issue open for now and I'll close it when I release the training code so that you get notified.

**Comment by aRI0U** [comment]
Hi! I just released the whole training pipeline in a separate repo, here is the link:
https://github.com/SonyCSLParis/pesto-full
